// Copyright 2026 Stefan Prodan.
// SPDX-License-Identifier: Apache-2.0
//
// The reply of the markdown shape: headings, lists, a table, a code
// block and a long paragraph, so a run measures the streaming render
// and the socket, not the model.

export const MARKDOWN_REPLY = [
  "## How GitHub rate limits work",
  "",
  "GitHub counts every REST call against a budget that resets each hour. An anonymous caller gets **60 requests per hour per source IP**, while a call signed with a token gets `5000`, and a GitHub App installation on Enterprise Cloud gets up to `15000`. The headers on every answer say where you stand, so a client never has to guess.",
  "",
  "- `x-ratelimit-limit` is the budget for the window",
  "- `x-ratelimit-remaining` is what is left of it",
  "- `x-ratelimit-reset` is when the window starts again, in epoch seconds",
  "- `x-ratelimit-used` counts what you spent",
  "- `x-ratelimit-resource` names the bucket, such as `core` or `search`",
  "",
  "## Secondary limits",
  "",
  "Beyond the hourly budget, GitHub also watches how fast you go. Too many concurrent requests, too many writes in a minute, or too much CPU time on its side all trip a *secondary* limit, answered with a 403 or a 429 and a `retry-after` header. These limits are not published as exact numbers on purpose, so the only safe client is one that backs off when told to and never retries in a tight loop.",
  "",
  "1. Keep concurrency low, ideally one request at a time per token",
  "2. Wait at least one second between writes",
  "3. Honour `retry-after` exactly, then add jitter",
  "4. Prefer conditional requests with `If-None-Match`, which cost nothing when the answer is a 304",
  "5. Use GraphQL when one query can replace many REST calls",
  "",
  "| Caller | Budget per hour | Bucket | Notes |",
  "|---|---|---|---|",
  "| Anonymous | 60 | core | per source IP |",
  "| Personal token | 5000 | core | per user |",
  "| GitHub App | 5000 to 15000 | core | scales with repos and users |",
  "| Actions `GITHUB_TOKEN` | 1000 | core | per repository |",
  "| Search | 30 per minute | search | separate bucket |",
  "| Code search | 10 per minute | code_search | separate bucket |",
  "",
  "## A client that behaves",
  "",
  "The loop below reads the headers on every answer and sleeps when the budget runs out, instead of hammering the API until it is blocked.",
  "",
  "```ts",
  "async function get(url: string, token: string): Promise<Response> {",
  "  for (;;) {",
  "    const res = await fetch(url, {",
  // biome-ignore lint/suspicious/noTemplateCurlyInString: code in the reply
  "      headers: { authorization: `Bearer ${token}` },",
  "    });",
  '    const remaining = Number(res.headers.get("x-ratelimit-remaining"));',
  '    const reset = Number(res.headers.get("x-ratelimit-reset"));',
  "    if (res.status === 403 || res.status === 429) {",
  '      const after = Number(res.headers.get("retry-after") ?? "60");',
  "      await Bun.sleep(after * 1000 + Math.random() * 1000);",
  "      continue;",
  "    }",
  "    if (remaining === 0) {",
  "      await Bun.sleep(Math.max(0, reset * 1000 - Date.now()));",
  "    }",
  "    return res;",
  "  }",
  "}",
  "```",
  "",
  "The same idea works in a shell script, where `curl -sI` prints the headers and a small `awk` reads the reset time before the next call, which is how most quick tools stay inside the limit without any library at all, and it is worth doing even for a one-off script because a blocked token stays blocked for the rest of the window and every other job that shares it stops too, which is the most common way a team discovers that three of its automations were quietly using the same personal token for months while nobody noticed until the morning they all failed together.",
  "",
  "### Checklist",
  "",
  "- [x] sign every call with a token",
  "- [x] read the headers on every answer",
  "- [ ] back off on 403 and 429",
  "- [ ] cache with ETags",
  "",
  "> A blocked token blocks every job that shares it, so give each automation its own.",
  "",
  "That is the whole picture: budget, headers, back off, and one token per job.",
  "",
].join("\n");
