apiVersion: v2
name: onectx
description: A self-hosted AI factory with continuous context.
type: application
version: 0.0.1
appVersion: "v0.0.1"
home: https://1ctx.dev
icon: https://1ctx.dev/icon.svg
sources:
  - https://github.com/stefanprodan/1ctx
maintainers:
  - name: Stefan Prodan
    url: https://github.com/stefanprodan
keywords:
  - agents
  - llm
annotations:
  artifacthub.io/license: Apache-2.0
