// Copyright 2026 Stefan Prodan.
// SPDX-License-Identifier: Apache-2.0
//
// The shell's fixed surface, apart from the limits, which pull in the
// database the command worker never opens. Commands are pinned so a
// dependency upgrade cannot silently expose a new runtime.

export const MAX_OPENS_PER_COMMAND = 10;
// the cap on a command's commands and on each loop, awk, sed and jq
export const COMMAND_ITERATIONS = 100_000;
// the interpreter stops at the call timeout and the worker is ended this
// long after, so the interpreter's exit 124, words and output win
export const BACKSTOP_MS = 1000;

export const KNOWLEDGE_COMMANDS = [
  "ls",
  "find",
  "tree",
  "cat",
  "head",
  "tail",
  "wc",
  "grep",
  "egrep",
  "fgrep",
  "rg",
  "sed",
  "awk",
  "gawk",
  "sort",
  "uniq",
  "cut",
  "tr",
  "diff",
  "comm",
  "join",
  "paste",
  "column",
  "nl",
  "tac",
  "rev",
  "fold",
  "expand",
  "unexpand",
  "jq",
  "yq",
  "xan",
  "base64",
  "tar",
  "gzip",
  "gunzip",
  "zcat",
  "date",
  "echo",
  "printf",
  "cp",
  "mv",
  "rm",
  "mkdir",
  "rmdir",
  "touch",
  "stat",
  "file",
  "ln",
  "basename",
  "dirname",
  "du",
  "env",
  "printenv",
  "pwd",
  "tee",
  "xargs",
  "seq",
  "expr",
  "true",
  "false",
  "sleep",
  "timeout",
  "md5sum",
  "sha1sum",
  "sha256sum",
  "od",
  "strings",
  "split",
  "readlink",
  "chmod",
  "which",
  "whoami",
  "hostname",
  "help",
  "bash",
  "sh",
  "time",
] as const;
